version: "3.1"
services:
  FreeDuckDuckGo:
    image: ghcr.io/missuo/freeduckduckgo:latest
    restart: always
    ports:
      - "3456:3456"
  
  portfolio-mate:
    build: .
    ports:
      - "8501:8501"
    restart: always
    depends_on:
      - FreeDuckDuckGo
